---
version: "3.9"

x-podman: &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

volumes:
  ovos_models:
    name: ovos_models
    driver: local
  ovos_vosk:
    name: ovos_vosk
    driver: local
  ovos_listener_records:
    name: ovos_listener_records
    driver: local
  ovos_tts_cache:
    name: ovos_tts_cache
    driver: local
  ovos_nltk:
    name: ovos_nltk
    driver: local
  ovos_local_state:
    name: ovos_local_state
    driver: local

services:
  ovos_messagebus:
    <<: *podman
    container_name: ovos_messagebus
    hostname: ovos_messagebus
    restart: unless-stopped
    image: docker.io/smartgic/ovos-messagebus:${VERSION}
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft

  ovos_phal:
    <<: *podman
    container_name: ovos_phal
    hostname: ovos_phal
    restart: unless-stopped
    image: docker.io/smartgic/ovos-phal:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: docker.for.mac.host.internal
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    privileged: true
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started

  ovos_phal_admin:
    <<: *podman
    container_name: ovos_phal_admin
    hostname: ovos_phal_admin
    restart: unless-stopped
    image: docker.io/smartgic/ovos-phal-admin:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    privileged: true
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - /dev:/dev:ro
    depends_on:
      ovos_messagebus:
        condition: service_started

  ovos_listener:
    <<: *podman
    container_name: ovos_listener
    hostname: ovos_listener
    restart: unless-stopped
    image: docker.io/smartgic/ovos-listener:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: docker.for.mac.host.internal
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_listener_records:/home/${OVOS_USER}/.local/share/mycroft/listener
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ovos_models:/home/${OVOS_USER}/.local/share/precise-lite
      - ovos_vosk:/home/${OVOS_USER}/.local/share/vosk
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_plugin_ggwave:
    <<: *podman
    container_name: ovos_plugin_ggwave
    hostname: ovos_plugin_ggwave
    restart: unless-stopped
    image: docker.io/smartgic/ovos-plugin-ggwave:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: docker.for.mac.host.internal
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_audio:
    <<: *podman
    container_name: ovos_audio
    hostname: ovos_audio
    restart: unless-stopped
    image: docker.io/smartgic/ovos-audio:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: docker.for.mac.host.internal
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ovos_tts_cache:/home/${OVOS_USER}/.cache/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_core:
    <<: *podman
    container_name: ovos_core
    hostname: ovos_core
    restart: unless-stopped
    image: docker.io/smartgic/ovos-core:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: docker.for.mac.host.internal
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ovos_nltk:/home/${OVOS_USER}/nltk_data
      - ${OVOS_SHARE_FOLDER}:/home/${OVOS_USER}/.local/share/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_cli:
    <<: *podman
    container_name: ovos_cli
    hostname: ovos_cli
    restart: unless-stopped
    image: docker.io/smartgic/ovos-cli:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started
