---
version: "3.9"

services:
  ovos_messagebus:
    healthcheck:
      disable: true

  ovos_phal:
    healthcheck:
      disable: true
    group_add:
      - "$AUDIO_GID"
      - "$GPIO_GID"
      - "$I2C_GID"
      - "$SPI_GID"

  ovos_phal_admin:
    healthcheck:
      disable: true
    group_add:
      - "$AUDIO_GID"
      - "$GPIO_GID"
      - "$I2C_GID"
      - "$SPI_GID"
  
  ovos_listener:
    healthcheck:
      disable: true

  ovos_audio:
    healthcheck:
      disable: true

  ovos_core:
    healthcheck:
      disable: true
    group_add:
      - "$AUDIO_GID"
      - "$GPIO_GID"
      - "$I2C_GID"
      - "$SPI_GID"
